"""Add completed column to tasks

Revision ID: 827f52cde7ba
Revises: 4e2a99c46271
Create Date: 2024-06-21 01:42:07.708420

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '827f52cde7ba'
down_revision = '4e2a99c46271'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('completed', sa.Boolean(), nullable=True))
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('to_do_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('complete')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('complete', sa.BOOLEAN(), nullable=True))
        batch_op.alter_column('to_do_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.drop_column('completed')

    # ### end Alembic commands ###
